### ISSUE TITLE
Build failures on BBS macOS builder (lconway)

### ISSUE THREAD

**Issue by PeteHaitch** [waldronlab/TENxIO#4]
Hi Marcel,

It was brought to my attention that **TENxIO** still not does not pass checks on [BBS macOS builder (lconway)](https://www.bioconductor.org/checkResults/3.18/bioc-LATEST/TENxIO/lconway-checksrc.html).
I raised this back in my review a year ago and [you said you'd keep an eye on it](https://github.com/Bioconductor/Contributions/issues/2753#issuecomment-1287046309).

So do you know if this error `Rhdf5lib was not compiled with support for the S3 VFD` has been occurring consistently for the last year or has it re-occurred more recently?

Thanks,
Pete

**Comment by LiNk-NY** [comment]
Hi Pete, @PeteHaitch 

Thanks for coming back to this. The error has not left because it is due to a configuration issue on the BBS Mac builder. 
Perhaps @jwokaty or @hpages can provide an update on the issue posted at https://github.com/Bioconductor/BBS/issues/245

For individual users, they may follow the guidance posted on the Bioconductor support site (and build from source): https://support.bioconductor.org/p/9134972/#9153268

I have tried Bioc Support Site advice and it does work. 

There was some discussion on the Bioconductor Community Slack as well: https://community-bioc.slack.com/archives/C35BSB5NF/p1614361779049000

The alternative is to skip the test when not configured for S3 VFD support. 

Best regards,
Marcel

**Comment by PeteHaitch** [comment]
Thanks, Marcel.
Moving to https://github.com/Bioconductor/BBS/issues/245.
